repository:
    description: What ever could this be?
    homepage: https://github.com/mattsb42/repo-admin

collaborators:
    -   username: mattsb42-admin-bot
        permission: admin

teams:
    -   name: bots
        permission: pull

labels:
    -   name: foo
        color: "336699"
        description: oh noes!
    -   name: bar
        color: "#339933"
        description: oh yeah!
    -   name: baz
        color: 000099
        description: this one has numbers for color!

branches:
    -   name: foo
        protection:
            required_pull_request_reviews:
                required_pull_review_count: 1
            required_status_checks: null
            enforce_admins: false
            restrictions: null
    -   name: bar
        protection:
            required_pull_request_reviews:
                required_pull_review_count: 1
            required_status_checks: null
            enforce_admins: false
            restrictions: null
