repository:
    description: What ever could this be?

collaborators:
    -   username: mattsb42-admin-bot
        permission: admin

labels:
    -   name: foo
        color: "336699"
        description: oh noes!
