on:
    push:
        branches:
            - master

collaborators:
    -   username: mattsb42-admin-bot
        permission: admin

jobs:
    apply-settings:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: mattsb42/repo-admin@init
                with:
                    github-token: ${{secrets.DAS_UBER_TOKEN}}
                    debug: true
