on:
    push:
        branches:
            - master

jobs:
    apply-settings:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: mattsb42/repo-admin@init
                with:
                    github-token: ${{secrets.ADMIN_TOKEN}}
